dist: trusty
sudo: required
language: php

git:
  depth: 1

env:
  global:
    - TEST="./vendor/bin/phpunit --verbose"
    - COMPOSER_UP="composer update --no-interaction --prefer-dist --no-progress --profile --no-suggest"
    - secure: "hmeMvb/32bjqu10h4bDE6k80j9Izggok4PXTJkQMUEt1BOlc93empSd9rF7QhbjVtPhgnY2fOd9ZUZoDWPNiW2r0+lXfYiCXO9zBKjzxEVa3jzCO1kkGGw1zfYej6tHn8aHmFhltpBl4/VhzIbON0k4JaPFjMAha2DIFlYs5sG3tspIHxllPusSnEvMBXg6F93fvl9fnW3VhpT2It8jE/oAGEHYV3O7mGY4RKnYFw1LMcpWSRLM3O/QFlI/Y8eEsoZSTbhYdmq/DBLQBbQk5exIu/waOVOK4y0MkeMlLWcpnHLC4JRZ+4ws97qtGMp4JcrOKmjuXsRSkwvlUZP/kfmXwY8kC3j2ZK7xLxsqH2CE1aRsV87J7bujQaIF4R+Ihf2FUP1oY7fTuYjW1WMx6hyr3cDbBbEdtIxKZj2dPnwbxr1ap7zz63ZEFuw4tt5Lwol8i88bwFqgTpgVBA2EQTo04+GLTa894+DB7+/8a5utB+2xW8sT+ZCCDgKbVQwtLh1k2WVWH8BIo3N6yyy3T/cSDyPCHEZQl2j72HcKmZXOOsnZUk/J8idM20/wxN4IC1n9fb2QaLR/8PCXbExV1X81kCMJ7ZnoknlvI5xm2QA588y7UWHQvM1WvdfX0ZF+CLVeLpIZmn9GKYJiVa2afKdvcW/SX6AkaoHhTG/d1Npc="

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - stty cols 120
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - chmod a+x ./build/travis/configure_php.sh
  - ./build/travis/configure_php.sh
  - composer validate

install:
  - composer global require hirak/prestissimo
  - $COMPOSER_UP

before_script:
  - chmod a+x ./build/travis/set_up_ssh.sh
  - ./build/travis/set_up_ssh.sh
  - wget https://cdn.rawgit.com/prisis/43a2a7b137998ac92e24ee4daaa8e296/raw/681b89b8e156750de46558ead661509c468fb9a2/try_catch.sh -P ./build/travis
  - wget https://cdn.rawgit.com/prisis/e050c4da44c6ee7fa1519912eac19563/raw/7a72a7df7718af30e703c1ef0379cdf7ff24ce10/tfold.sh -P ./build/travis

jobs:
  include:
    - stage: Test
      if: NOT type = cron
      php: 7.4
      env: REMOVE_XDEBUG=true
      script:
        - chmod a+x ./build/travis/script.sh
        - ./build/travis/script.sh

    - stage: Build
      if: type = cron
      php: 7.4
      env: REMOVE_XDEBUG=true
      before_script:
        - stty cols 120
        - |
          git config --global user.email "$GH_USER_EMAIL"
          git config --global user.name "$GH_USER_NAME"
          git remote set-url origin git@github.com:narrowspark/security-advisories.git
        - |
          chmod a+x ./build/travis/set_up_ssh.sh
          ./build/travis/set_up_ssh.sh
      script:
        - php cerebro build
        - php cerebro commit
        - rm -fr ./build/git/*

notifications:
  email:
    on_success: never
    on_failure: always
