dist: trusty
sudo: required
language: php

env:
  global:
    - TEST="./vendor/bin/phpunit --verbose"
    - COMPOSER_UP="composer update --no-interaction --prefer-dist --no-progress --profile --no-suggest"

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

before_install:
  - stty cols 120
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - |
    chmod a+x ./build/travis/configure_php.sh
    chmod a+x ./build/travis/script.sh
  - ./build/travis/configure_php.sh
  - composer validate

install:
  - composer global require hirak/prestissimo
  - $COMPOSER_UP

before_script:
  - wget https://cdn.rawgit.com/prisis/43a2a7b137998ac92e24ee4daaa8e296/raw/681b89b8e156750de46558ead661509c468fb9a2/try_catch.sh -P ./build/travis
  - wget https://cdn.rawgit.com/prisis/e050c4da44c6ee7fa1519912eac19563/raw/7a72a7df7718af30e703c1ef0379cdf7ff24ce10/tfold.sh -P ./build/travis

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - stage: Test
      php: 7.2
      env: PHPUNIT=true REMOVE_XDEBUG=true
      script:
        - ./build/travis/script.sh

    - stage: Coding standard
      php: 7.2
      env: REMOVE_XDEBUG=true
      script:
        - ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

    - stage: Static Analysis
      php: 7.2
      env: REMOVE_XDEBUG=false
      script:
        - ./vendor/bin/phpstan analyse -c phpstan.neon -l 7 src

    - stage: Build
      php: 7.2
      env: REMOVE_XDEBUG=true
      script:
        - php cerebro build
        - php cerebro commit

notifications:
  email:
    on_success: never
    on_failure: change
