# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - automerged_updates:
      - match:
          dependency_type: "development"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    directory: "/"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    default_labels:
      - "dependency"
      - "Changed"
